name: Deploy

on: release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to crates.io
      run: cargo publish --token="${{ secrets.CRATES_IO_TOKEN }}"
