name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  releases:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Deploy to crates.io
      run: cargo publish --token="${{ secrets.CRATES_IO_TOKEN }}"
